### ISSUE TITLE
Update Maven and Git for Docking Frames version

### ISSUE THREAD

**Issue by nicolas-f** [Benoker/DockingFrames#33]
Hello,

Some remarks on DockingFrames versions.

# Maven

The version is not up to date in maven. You should replace `<version>1.1.2-P8c</version>` by `<version>1.1.2-P14c</version>` in all pom.xml files.

# Git

Versions from 1.1.2p8e are not tagged in git. Moreover you should separate revision (2) and custom [software versioning](http://en.wikipedia.org/wiki/Software_versioning)

Thanks

**Comment by Benoker** [comment]
pom files are updated - I task myself to write a script that updates the files automatically.

**Comment by Benoker** [comment]
From now on every time I build the project the pom-files are updated with the contents of the "version" file.
