### ISSUE TITLE
"area" attribute is not loaded if xml format is used to persist layout

### ISSUE THREAD

**Issue by 4eTi** [Benoker/DockingFrames#36]
Reproduced in 1.1.1 and 1.1.2-SNAPSHOT. Binary format works fine.

step to reproduce:
1. create perspective with internal working area and dockables
2. save to xml
3. load from xml
area fields for Dockables are empty after load.

Seems like mistyping in  class CommonSingleDockableFactory in method

 public CommonSingleDockableLayout read( XElement element, PlaceholderStrategy placeholders ) {
        CommonSingleDockableLayout layout = new CommonSingleDockableLayout();
    	
    	layout.setId( element.getElement( "id" ).getString() );
    	
    	XElement xarea = element.getElement( "area" );
    	if( xarea != null ){
    		String area = element.getString(); <----- here. should xarea.getString should be used instead?
    		if( "".equals( area )){
    			layout.setArea( null );
    		}
    		else{
    			layout.setArea( area );
    		}
    	}
        
    	return layout;
    }

**Comment by Benoker** [comment]
You are right, I'll fix this for the next version (next weekend).

**Comment by 4eTi** [comment]
Thanks!

**Comment by Benoker** [comment]
Fix is checked in :-)
