### ISSUE TITLE
No destination/target info in Inserter?

### ISSUE THREAD

**Issue by adam-law** [Benoker/DockingFrames#62]
Hi,

I'm testing out the framework and couldn't find if there was any information about the drop destination that can be used in the implementation of Inserter.  I do see the source/candidate info

If it's not there, why not, or is there some other way to get this info? I'm trying to filter drops on a certain area, to only dockables with a specific title or ID.

Thanks!

**Comment by Benoker** [comment]
You mean you need the location of the mouse for the decision? That information is no longer available for the Inserter, because it was already used to build the "StationDropOperation".

Maybe the VetoableDockRelocatorListener would be better for you, because the "DockRelocatorEvent" includes all the information that "Inserter" receives plus the location of the mouse. And if you override the "searched" method and call "DockRelocatorEvent.forbid", then all the animations should still work out correctly.

**Comment by adam-law** [comment]
Thanks for the quick reply! VetoableDockRelocatorListener sounds close to what I need. Apart from the mouse location, does it supply other info on the "destination"? 

For example, I want to drag dock1 over dock2, but dock2 only accepts docks of a certain type, or maybe ID. Since CDocks can be given a unique ID, I was hoping to pull the destination docks ID for the check, and allow or veto the drop, accordingly. 

As an alternative, if this check can be done by a handler on the destination dock, that can work too.

Of course, if there is a method in the framework to accomplish this, using the mouse location, then I'll be happy to use that too.

Thanks!

**Comment by Benoker** [comment]
3 options I have to provide:

If you just want to prevent Dockables from being stacked in any case, you can use the `setStackable` method:

	DefaultSingleCDockable dockable = ...
	dockable.setStackable( false );


First I was thinking you want to filter the drop location by the ID of the parent station? Like this:

	package test;
	
	import java.awt.GridLayout;
	
	import javax.swing.JFrame;
	
	import bibliothek.gui.DockStation;
	import bibliothek.gui.Dockable;
	import bibliothek.gui.dock.common.CControl;
	import bibliothek.gui.dock.common.CStation;
	import bibliothek.gui.dock.common.DefaultSingleCDockable;
	import bibliothek.gui.dock.control.relocator.DockRelocatorEvent;
	import bibliothek.gui.dock.control.relocator.VetoableDockRelocatorAdapter;
	
	public class ListenerTest {
		public static void main( String[] args ) {
			JFrame frame = new JFrame( "Test" );
			frame.setBounds( 50, 50, 1000, 1000 );
	
			CControl control = new CControl( frame );
	
			frame.setLayout( new GridLayout( 2, 2 ) );
	
			frame.add( control.createGridArea( "A" ).getComponent() );
			frame.add( control.createGridArea( "B" ).getComponent() );
			frame.add( control.createGridArea( "C" ).getComponent() );
			frame.add( control.createGridArea( "D" ).getComponent() );
	
			DefaultSingleCDockable dockable = new DefaultSingleCDockable( "dockable" );
			control.addDockable( dockable );
			dockable.setLocation( control.getStation( "A" ).getDropLocation() );
			dockable.setVisible( true );
	
			// add listener to controller
			control.getController().getRelocator().addVetoableDockRelocatorListener( new VetoableDockRelocatorAdapter() {
				// ... when searching a new target ...
				public void searched( DockRelocatorEvent event ) {
					// convert target to "CStation" to read unique id
					DockStation target = event.getTarget();
					CStation<?> station = control.getStation( target );
	
					// walk along the path to the root station until first real CStation is found
					while( target != null && station == null ) {
						Dockable asDockable = target.asDockable();
						if( asDockable == null ) {
							target = null;
						} else {
							target = asDockable.getDockParent();
						}
						if( target != null ) {
							station = control.getStation( target );
						}
					}
	
					// if unique id of station matches B, do not allow the target to be used
					if( station != null && station.getUniqueId().equals( "B" ) ) {
						event.forbid();
					}
				}
			} );
	
			frame.setVisible( true );
		}
	}

But I guess you really do not want two specific Dockables to be put in the same stack? Then you will have to use the very old API of `DockAcceptances`:

	package test;
	
	import javax.swing.JFrame;
	
	import bibliothek.gui.DockStation;
	import bibliothek.gui.Dockable;
	import bibliothek.gui.dock.StackDockStation;
	import bibliothek.gui.dock.accept.DockAcceptance;
	import bibliothek.gui.dock.common.CControl;
	import bibliothek.gui.dock.common.CGrid;
	import bibliothek.gui.dock.common.DefaultSingleCDockable;
	import bibliothek.gui.dock.common.SingleCDockable;
	import bibliothek.gui.dock.common.intern.CDockable;
	import bibliothek.gui.dock.common.intern.CommonDockable;
	
	public class ListenerTest {
		public static void main( String[] args ) {
			JFrame frame = new JFrame( "Test" );
			frame.setBounds( 50, 50, 1000, 1000 );
	
			CControl control = new CControl( frame );
	
			frame.add( control.getContentArea() );
	
			CGrid grid = new CGrid( control );
			grid.add( 0, 0, 1, 1, new DefaultSingleCDockable( "a", "A" ) );
			grid.add( 0, 1, 1, 1, new DefaultSingleCDockable( "b", "B" ) );
			grid.add( 1, 0, 1, 1, new DefaultSingleCDockable( "c", "C" ) );
			grid.add( 1, 1, 1, 1, new DefaultSingleCDockable( "d", "D" ) );
			control.getContentArea().deploy( grid );
	
			control.getController().addAcceptance( new DockAcceptance() {
				@Override
				public boolean accept( DockStation parent, Dockable child, Dockable next ) {
					// a new stack is about to be created
					return allowedToBeInTheSameStack( child, next );
				}
	
				@Override
				public boolean accept( DockStation parent, Dockable child ) {
					if( parent instanceof StackDockStation ) {
						// putting "child" on a stack that already exists
						for( int i = 0, n = parent.getDockableCount(); i < n; i++ ) {
							if( !allowedToBeInTheSameStack( child, parent.getDockable( i ) ) ) {
								return false;
							}
						}
					}
	
					return true;
				}
			} );
	
			frame.setVisible( true );
		}
	
		// tell if d1 and d2 are allowed in the same stack - "a" and "b" are not allowed to be in the same stack
		private static boolean allowedToBeInTheSameStack( Dockable d1, Dockable d2 ) {
			if( d1 == d2 ) {
				return true;
			}
	
			String id1 = getId( d1 );
			String id2 = getId( d2 );
	
			System.out.println( "comparing " + id1 + " and " + id2 );
	
			return !("a".equals( id1 ) || "a".equals( id2 ) && ("b".equals( id1 ) || "b".equals( id2 )));
		}
	
		// extract unique id of a Dockable
		private static String getId( Dockable dockable ) {
			if( dockable instanceof CommonDockable ) {
				CDockable cdockable = ((CommonDockable) dockable).getDockable();
				if( cdockable instanceof SingleCDockable ) {
					return ((SingleCDockable) cdockable).getUniqueId();
				}
			}
			return null;
		}
	}

**Comment by adam-law** [comment]
These look great! Thanks for taking the time! :) I'll test it out today when I get home and let you know how it goes :)

**Comment by adam-law** [comment]
I've tried the 3, and here's my feedback:
- setStackable(false) doesn't seem to work. The Dockable still accepted other docks dropped on it.
- The 2nd option is the exact behavior I'm looking for, though I want to filter via the unique ID of the Dockable. 

I've tried merging the idea of the 2nd and 3rd options, but it doesn't seem to work with "Dockable on Dockable" drops. Dockables seem to have an internal CenterStation with a unique ID that cannot be changed, nor was I able to do a instanceof comparison for CenterStation (hidden class it seems).

If there is a way to set the CenterStation's id, this would work perfectly.

- While the 3rd option has the UID comparison I was looking for, unlike the 2nd option, it causes the denying Dockable to still animate and try to make room for the drop candidate. If there's a way to prevent this animation and resizing behavior, then this too can be perfect :)

Thank you!

**Comment by Benoker** [comment]
You can get the ID of the center-station like this:

	CControl control = ... ;
	CContentArea contentArea = control.getContentArea();
	String centerId = contentArea.getCenterIdentifier();

The `centerId` will always be a combination of a unique String (from `CControl.createContentArea`) and the constant `center`.

The animation happens because the code assumes that the Dockables may still be neighbors. Neighbors is not a concept the framework understands. You only have the choice between not dropping on the parent station at any place, or allowing neighbors.

If you just want to disable the animation, but allow neighbors, you would need to override `DockTheme.SPAN_FACTORY` property (that would just be a cosmetic change).

**Comment by adam-law** [comment]
Sorry, I think my observations were mistaken. I thought each CDockable had an internal station, but I gather this center area is the actual content area's station?

On the other point, what if I want to disallow neighbors? I think if I disallow drops, and prevent neighbors, I will achieve the effect I want.

**Comment by Benoker** [comment]
Dockables and stations build trees - just like other Swing components. Dockables are always the leafs in this tree, while the stations define root or nodes.
Normally there are 6 roots when using DockingFrames:
- the center area
- the minimizie areas to the left, right, top and bottom
- the floating layer aka `ScreenDockStation`

A Dockable will always be a child of a center area, never the other way around. A Dockable may provide a `content area`, but thats just an empty `JPanel` on which clients can put their Buttons, Textfields, etc.


About neighbors. I'm not certain if we speak about the same thing. In the picture what are the neighbours of "D"?
![image](https://user-images.githubusercontent.com/813584/38751975-fcf0b868-3f59-11e8-8cbc-4b0dd6fcd004.png)
In my understanding "B" and "C" are neighbors of "D", but "A" is not a neighbor (nor is "E").

There are some shady ways with which you could prevent for example "A" from being placed directly as neighbor to "D". But you cannot prevent a user from just (re)moving "B".

(Shady ways include replacing the `CControlFactory`, overriding `createSplitDockStation` and return a custom implementation of a `CSplitDockStation` where methods like `prepareDrop` are overriden... it's a lot of work).

**Comment by adam-law** [comment]
Ah, thank you for the clarifications! With regard to neighbors, we are indeed of the same mind.

Perhaps I need to expound further. When I tested out your DockAcceptance example, it did indeed prevent stacking, but the process then proceeded to making room adjacent to the denying dock, animating the process. If at all possible, I want to prevent even that, and if the user releases the mouse hold, the drop candidate will revert back to its original position. instead of becoming a neighbor.

My ultimate goal, combining all the topics I've opened up, is to hopefully have the visual component at the "bottom", fully expanded, and docks above it and cannot be resized by them. As it is, if I make the VC a dock, it is subject to resizing when its neighbors are not floating or minimized. 

Future visual eye candy will use your suggestions for transparent components to have translucent docks still showing the VC running underneath, without being completely transparent.

With that being said, I am quite happy with the layout, and placement abilities of your framework and things are looking really good, with minimal effort :)

**Comment by Benoker** [comment]
Alright, here is some code to play around with. It will disable neighbors for the A and B dockable. There might be unwanted side effects, as we are diving deep into the library now (you are probably the only person that is ever going to use code like this). I suggest you play a bit around with the code.

The idea here is to install a custom `CLockedResizeLayoutManager`, which is the object that decides how exactly the center-area (which is a `SplitDockStation`) behaves. 

	package test;
	
	import javax.swing.JFrame;
	
	import bibliothek.gui.DockStation;
	import bibliothek.gui.Dockable;
	import bibliothek.gui.dock.SplitDockStation;
	import bibliothek.gui.dock.StackDockStation;
	import bibliothek.gui.dock.accept.DockAcceptance;
	import bibliothek.gui.dock.common.CControl;
	import bibliothek.gui.dock.common.CGrid;
	import bibliothek.gui.dock.common.DefaultSingleCDockable;
	import bibliothek.gui.dock.common.SingleCDockable;
	import bibliothek.gui.dock.common.intern.CDockable;
	import bibliothek.gui.dock.common.intern.CommonDockable;
	import bibliothek.gui.dock.common.intern.station.CLockedResizeLayoutManager;
	import bibliothek.gui.dock.station.split.Leaf;
	import bibliothek.gui.dock.station.split.PutInfo;
	import bibliothek.gui.dock.station.split.PutInfo.Put;
	
	public class ListenerTest {
		public static void main( String[] args ) {
			JFrame frame = new JFrame( "Test" );
			frame.setBounds( 50, 50, 1000, 1000 );
	
			CControl control = new CControl( frame );
	
			// install customized layout manager
			control.putProperty( SplitDockStation.LAYOUT_MANAGER, new CustomCLockedResizeLayoutManager( control ) );
	
			frame.add( control.getContentArea() );
	
			CGrid grid = new CGrid( control );
			grid.add( 0, 0, 1, 1, new DefaultSingleCDockable( "a", "A" ) );
			grid.add( 0, 1, 1, 1, new DefaultSingleCDockable( "b", "B" ) );
			grid.add( 1, 0, 1, 1, new DefaultSingleCDockable( "c", "C" ) );
			grid.add( 1, 1, 1, 1, new DefaultSingleCDockable( "d", "D" ) );
			control.getContentArea().deploy( grid );
	
			control.getController().addAcceptance( new DockAcceptance() {
				@Override
				public boolean accept( DockStation parent, Dockable child, Dockable next ) {
					// a new stack is about to be created
					return allowedToBeInTheSameStack( child, next );
				}
	
				@Override
				public boolean accept( DockStation parent, Dockable child ) {
					if( parent instanceof StackDockStation ) {
						// putting "child" on a stack that already exists
						for( int i = 0, n = parent.getDockableCount(); i < n; i++ ) {
							if( !allowedToBeInTheSameStack( child, parent.getDockable( i ) ) ) {
								return false;
							}
						}
					}
	
					return true;
				}
			} );
	
			frame.setVisible( true );
		}
	
		// tell if d1 and d2 are allowed in the same stack - "a" and "b" are not allowed to be in the same stack
		private static boolean allowedToBeInTheSameStack( Dockable d1, Dockable d2 ) {
			if( d1 == d2 ) {
				return true;
			}
	
			String id1 = getId( d1 );
			String id2 = getId( d2 );
	
			System.out.println( "comparing " + id1 + " and " + id2 );
	
			return !(("a".equals( id1 ) || "a".equals( id2 )) && ("b".equals( id1 ) || "b".equals( id2 )));
		}
	
		// extract unique id of a Dockable
		private static String getId( Dockable dockable ) {
			if( dockable instanceof CommonDockable ) {
				CDockable cdockable = ((CommonDockable) dockable).getDockable();
				if( cdockable instanceof SingleCDockable ) {
					return ((SingleCDockable) cdockable).getUniqueId();
				}
			}
			return null;
		}
	
		// customized layout manager filtering neighbors
		private static class CustomCLockedResizeLayoutManager extends CLockedResizeLayoutManager {
			public CustomCLockedResizeLayoutManager( CControl control ) {
				super( control );
			}
	
			@Override
			public PutInfo validatePutInfo( SplitDockStation station, PutInfo info ) {
				info = super.validatePutInfo( station, info );
				if( info == null ) {
					return null;
				}
	
				if( info.getPut() == Put.TITLE || info.getPut() == Put.CENTER ) {
					return info;
				}
	
				if( info.getNode() instanceof Leaf ) {
					Dockable neighbor = ((Leaf) info.getNode()).getDockable();
					if( !allowedToBeInTheSameStack( neighbor, info.getDockable() ) ) {
						info = null;
					}
				}
	
				return info;
			}
		}
	}

**Comment by adam-law** [comment]
Wow! Thank you for putting this together! I'll test it out ASAP and let you know how it goes :)

**Comment by adam-law** [comment]
Works great; just what I needed. Thanks!
