### ISSUE TITLE
Transparent background CContentArea

### ISSUE THREAD

**Issue by adam-law** [Benoker/DockingFrames#63]
Is there a part of the code that keeps the CContentArea's background opaque? Or do CCStations have a background too?

I tried extending and overriding the content area's class, to make it transparent, but it doesn't take. I can change the color of its background, however, so I think i'm in the right place.

I'm trying to make it transparent so I can overlay/stack DockingFrames, over another component that presents a visual display.

**Comment by adam-law** [comment]
Wow. I could have sworn I did a repo search for "transparent"/"transparency". Thanks for the tip!

**Comment by adam-law** [comment]
I haven't had the time to review all transparency-related search rseults, but I've reviewed the example and it'll be great for future work, but I want to ask, is there a method to get to the actual CContentArea's background? I still want the CDockable's to be opaque, but where there isn't a Dockable, I want it to be see-thru, to the underlying layer that displays my visuals.

**Comment by Benoker** [comment]
You will have to combine the example and your old code I guess. `CContentArea` is just a `JPanel`, so you can set it transparent directly.

![image](https://user-images.githubusercontent.com/813584/38692994-da6ffe40-3e85-11e8-817e-30f2a0115f1d.png)

	package test;
	
	import javax.swing.JButton;
	import javax.swing.JFrame;
	import javax.swing.JLayeredPane;
	
	import bibliothek.gui.DockTheme;
	import bibliothek.gui.dock.common.CContentArea;
	import bibliothek.gui.dock.common.CControl;
	import bibliothek.gui.dock.common.CGrid;
	import bibliothek.gui.dock.common.DefaultSingleCDockable;
	import bibliothek.gui.dock.util.BackgroundPaint;
	
	public class TransparencyTest {
		public static void main( String[] args ) {
			JFrame frame = new JFrame( "Test" );
			frame.setBounds( 50, 50, 1000, 1000 );
			CControl control = new CControl( frame );
	
			// some components
			JButton button = new JButton( "background" );
			button.setOpaque( false );
	
			// set content are transparent
			CContentArea contentArea = control.getContentArea();
	
			contentArea.setOpaque( false );
			contentArea.getNorthArea().setOpaque( false );
			contentArea.getSouthArea().setOpaque( false );
			contentArea.getEastArea().setOpaque( false );
			contentArea.getWestArea().setOpaque( false );
	
			// set everything else transparent
			control.putProperty( DockTheme.BACKGROUND_PAINT, BackgroundPaint.TRANSPARENT );
	
			// but button behind content-area
			JLayeredPane layers = new JLayeredPane() {
				{
					add( button );
					add( contentArea );
	
					setLayer( button, 1 );
					setLayer( contentArea, 2 );
				}
	
				@Override
				public void doLayout() {
					button.setBounds( 0, 0, getWidth(), getHeight() );
					contentArea.setBounds( 0, 0, getWidth(), getHeight() );
				}
			};
	
			frame.add( layers );
	
			CGrid grid = new CGrid( control );
			grid.add( 0, 0, 1, 1, new DefaultSingleCDockable( "a", "A" ) );
			grid.add( 0, 1, 1, 1, new DefaultSingleCDockable( "b", "B" ) );
			grid.add( 1, 0, 1, 1, new DefaultSingleCDockable( "c", "C" ) );
			grid.add( 1, 1, 1, 1, new DefaultSingleCDockable( "d", "D" ) );
			contentArea.deploy( grid );
	
			frame.setVisible( true );
		}
	}

If you want even more control over the background of `CContentArea`, then you need to subclass it (I would not recommend it however, prefer composition over inheritance).

**Comment by adam-law** [comment]
It looks great and works well. Unfortunately, there's a hitch, and I'm afraid it might fall outside the bounds of what you can or want to answer.

The main visual display is actually an OpenGL canvas. Apparently, mixing it up the way you prescribed causes the transparent CContentArea, to become opaque again. I discovered it by tracing that the OpenGL canvas works properly (i.e. it renders continuously), and halving the bounds of the CContentArea, showing the canvas that's quietly running underneath.

I've also tried creating a 2nd content area, putting the OGL canvas on the default one, and setting the docks on the 2nd content area, with the same results: transparent components become opaque.

I don't suppose you have any idea? You're expertise in Swing, is quite obvious :)

**Comment by Benoker** [comment]
I would have expected that the canvas paints over the Swing components, regardless of any other settings one can make. Because a canvas is something from the AWT world.

Which OpenGL canvas are you using?

**Comment by adam-law** [comment]
Oh I'm just going by observation. I'm not sure yet what's going on, apart from the opacity getting reverted to opaque.

I'm using an LWJGL- based canvas.

**Comment by Benoker** [comment]
Pfffff .... I could not find anything that helps. Maybe you should ask the developers of LWJGL directly?

**Comment by adam-law** [comment]
Yeah, me too. Even general topics regarding AWT <> Swing don't speak of it much. I'll drop them a post and if it's fruitful, I'll create a thread in your forum :) Thank you!
