### ISSUE TITLE
Persistence with MissingCDockableStrategy.STORE

### ISSUE THREAD

**Issue by devmagix** [Benoker/DockingFrames#65]
I'm having an issue with persistence. It is similar to [issue 28](https://github.com/Benoker/DockingFrames/issues/28) but is not quite the same. In my application, I need to add MultipleCDockableFactories after loading the persistence file with CControl.readXML. The CControl.setMissingStrategy is set to MissingCDockableStrategy.STORE, so that the factories will effectively be called when added if matching dockables have been loaded previously.
It works... except when docks are stacked into tabs. One of the tabbed docks, when reloading, is made invisible by the framework (i.e. not available in the docks list menu) but its content stays in the working area, which is weird because it cannot be closed. It is fixed if configuration is reloaded afterwards, but unfortunately this is not an option in my case.

I don't know if what I write makes any sense :) so I reproduced the issue with the paint demo. See attached modified sources. Tested with 1.1.2-P20b.
[ViewManager.java.txt](https://github.com/Benoker/DockingFrames/files/2307117/ViewManager.java.txt)
[Core.java.txt](https://github.com/Benoker/DockingFrames/files/2307118/Core.java.txt)
Try to create 3 editor tabs, close, restart: one of the 3 tabs is not closeable and not available in the View menu.

So my question is: is this a bug, or adding factories after loading configuration is not supposed to be supported? Thanks.

(Note: Thanks for this framework, I love it!)

**Comment by Benoker** [comment]
I'll try out your demo (maybe not before the weekend). In theory what you are doing should be possible, but you are scratching the limits. I'll report back when I know more (most certainly not before the weekend).

**Comment by Benoker** [comment]
I found part of the solution. There is a piece of code that cleans up old layout information, that piece of code cleans up too much. It did throw away the "stack". Making it more intelligent did help a bit, but the layout is still not loaded properly. I'll keep investigating.

**Comment by Benoker** [comment]
Also fixed a second bug where the newly created Dockables were not registered properly (and thus did not have any buttons).

I'll commit, push and upload 1.1.2p20c later today

**Comment by devmagix** [comment]
Thanks a lot! I'll try it on monday.

Le sam. 25 août 2018 à 11:41, Benjamin Sigg <notifications@github.com> a
écrit :

**Comment by devmagix** [comment]
Just tested the new version, I confirm it works for me now.
Thanks again!

**Comment by Benoker** [comment]
Thank you. Let me know if you have any other issues.
